Revert typeahead to 0.10.x version, v0.11.x throws exception (#1011)
Exception:
java.lang.IllegalArgumentException: Not valid encoding '%QU'

(cherry picked from commit 6764c94c4486a09b2af9779a82a90fe881c49b28)